{ config, pkgs, ... }:

{
  imports = [
    ./gaming/gaming.nix
    ./hardware/nvidia.nix
    ./hardware/opengl.nix
    ./mail/isync.nix
    ./mail/lynx.nix
    ./mail/msmtp.nix
    ./mail/mw.nix
    ./mail/neomutt.nix
    ./programs/wayland/hyprland.nix
    ./programs/fastfetch.nix
    ./programs/git.nix
    ./programs/kitty.nix
    ./programs/latex.nix
    ./programs/librewolf.nix
    ./programs/mpv.nix
    ./programs/neovim.nix
    ./programs/newsboat.nix
    ./programs/nsxiv.nix
    ./programs/obs-studio.nix
    # ./programs/obs.nix
    ./programs/pcmanfm.nix
    ./programs/rofi.nix
    ./programs/sddm.nix
    ./programs/swaync.nix
    ./security/gpg.nix
    ./security/pass.nix
    ./security/security.nix
    ./shell/aliasrc.nix
    ./shell/profile.nix
    ./shell/zsh.nix
    ./system/audio.nix
    ./system/bluetooth.nix
    ./system/fonts.nix
    ./system/gnome.nix
    ./system/keyboard.nix
    ./system/localization.nix
    ./system/mimeapps.nix
    ./system/networking.nix
    ./system/packages.nix
    ./system/services.nix
    ./system/system.nix
    ./system/users.nix
    ./virtualization/virtualbox.nix
  ];
}
