{ config, lib, pkgs, ... }:

{
  environment.shellAliases = {
    # Existing aliases
    cp = "cp -iv";
    mv = "mv -iv";
    rm = "rm -vI";
    bc = "bc -ql";
    rsync = "rsync -avPh";
    mkd = "mkdir -pv";
    yt = "yt-dlp --embed-metadata -i";
    yta = "yt -x -f bestaudio/best";
    ytt = "yt --skip-download --write-thumbnail";
    ffmpeg = "ffmpeg -hide_banner";
    ls = "ls -hN --color=auto --group-directories-first";
    la = "ls -AhN --color=auto --group-directories-first";
    ll = "ls -lA --color=auto --group-directories-first";
    eza = "eza -a --group-directories-first";
    lt = "eza --tree --level=2 --long --icons --git";
    grep = "grep --color=auto";
    diff = "diff --color=auto";
    ccat = "highlight --out-format=ansi";
    ip = "ip -color=auto";
    ka = "killall";
    g = "git";
    trem = "transmission-remote";
    YT = "youtube-viewer";
    sdn = "shutdown -h now";
    e = "$EDITOR";
    v = "$EDITOR";
    p = "pacman";
    xi = "sudo xbps-install";
    xr = "sudo xbps-remove -R";
    xq = "xbps-query";
    z = "nohup zathura >/dev/null 2>&1 & ";
    ".." = "cd ..";
    "..." = "cd ../..";
    "...." = "cd ../../..";
    "....." = "cd ../../../..";
    "......" = "cd ../../../../..";
    
    # Newly added aliases from shortcutrc
    cac = "cd /home/jonash/.cache && ls -A";
    cf = "cd /home/jonash/.config && ls -A";
    D = "cd /home/jonash/Downloads && ls -A";
    d = "cd /home/jonash/Documents && ls -A";
    dt = "cd /home/jonash/.local/share && ls -A";
    rr = "cd /home/jonash/.local/src && ls -A";
    h = "cd /home/jonash && ls -A";
    m = "cd /home/jonash/Music && ls -A";
    mn = "cd /mnt && ls -A";
    pp = "cd /home/jonash/Pictures && ls -A";
    sc = "cd /home/jonash/.local/bin && ls -A";
    src = "cd /home/jonash/.local/src && ls -A";
    vv = "cd /home/jonash/Videos && ls -A";
    tt = "cd /home/jonash/Videos/tv-shows/ && ls -A";
    bf = "$EDITOR /home/jonash/.config/shell/bm-files";
    bd = "$EDITOR /home/jonash/.config/shell/bm-dirs";
    cfx = "$EDITOR /home/jonash/.config/x11/xresources";
    cfb = "$EDITOR ~/.local/src/dwmblocks/config.h";
    cfv = "$EDITOR /home/jonash/.config/nvim/lua/config/lazy.lua";
    cfz = "$EDITOR /home/jonash/.config/zsh/.zshrc";
    cfa = "$EDITOR /home/jonash/.config/shell/aliasrc";
    cfp = "$EDITOR /home/jonash/.config/shell/profile";
    cfm = "$EDITOR /home/jonash/.config/mutt/muttrc";
    cfn = "$EDITOR /home/jonash/.config/newsboat/config";
    cfu = "$EDITOR /home/jonash/.config/newsboat/urls";
    cfmb = "$EDITOR /home/jonash/.config/ncmpcpp/bindings";
    cfmc = "$EDITOR /home/jonash/.config/ncmpcpp/config";
    cfl = "$EDITOR /home/jonash/.config/lf/lfrc";
    cfL = "$EDITOR /home/jonash/.config/lf/scope";
    cfX = "$EDITOR /home/jonash/.config/nsxiv/exec/key-handler";
    sn = "$EDITOR ~/.local/share/larbs/snippets";
    
    # Your other existing aliases
    school = "cd ~/Insync/hestdahl@gmail.com/School/Bachelor\\ Ingeniørfag/Bachelor\\ Ingeniørfag\\ -\\ Bygg && ls -lahN";
    so = "source ~/.config/zsh/.zshrc";
    calc = "speedcrunch";
    sus = "sudo systemctl suspend";
    ym = "youtube-music";
    notion = "notion-app";
    focus = "mpv /home/jonash/Music/Smoothed\\ Brown\\ Noise\\ 8-Hours\\ -\\ Remastered,\\ for\\ Relaxation,\\ Sleep,\\ Studying\\ and\\ Tinnitus.mp4";
    cal = "cal -m -w -3";
    gconfig = "/usr/bin/git --git-dir=$HOME/dotfiles --work-tree=$HOME";
    code = "cd ~/repos/github/code/ && ll || ls -lh";
    s = "speedtest";
    b = "blueman-manager";
    jblcharge5_disconnect="echo -e 'disconnect F8:5C:7D:67:B9:14' | bluetoothctl" ;
    pxc550="echo -e 'connect 00:16:94:23:F3:FF' | bluetoothctl" ;
    pxc550_disconnect="echo -e 'disconnect 00:16:94:23:F3:FF' | bluetoothctl" ;
    sony_headphones="echo -e 'connect AC:80:0A:3A:5E:12' | bluetoothctl" ;
    sony_headphones_disconnect="echo -e 'disconnect AC:80:0A:3A:5E:12' | bluetoothctl" ;
    sony_earplugs="echo -e 'connect   F8:4E:17:CF:40:B8' | bluetoothctl" ;
    sony_earplugs_disconnect="echo -e 'disconnect   F8:4E:17:CF:40:B8' | bluetoothctl" ;
    pm = "pulsemixer";
    py = "python";
    finance = "cd /home/jonash/Documents/finance";
    ns = "sudo nvidia-settings";
    apps = "cd ~/apps && ls";
    books = "cd ~/Books && ls";
    lw = "librewolf";
    signal = "signal-desktop";
    kamera = "cd ~/Syncthing/pixel6a-kamera/ && ls";
    pi = "echo 'scale=10; 4*a(1)' | bc -l";
    pyvenv = "source ~/python-venv/bin/activate";
    pyvenv_deactivate = "deactivate";
    clock = "tty-clock -c -f '%a %d %b %H:%M'";
    dotfiles = "cd ~/dotfiles-nix && ls";
    sxiv = "nsxiv";
    hst = "history 1 -1 | cut -c 8- | sort | uniq | fzf | tr -d '\\n' | xclip -sel c";
    gpumonitor = "watch -n 2 nvidia-smi";
    bottles = "flatpak run com.usebottles.bottles";
    todo = "bat ~/obsidian/TODO.md";
    newnet = "sudo systemctl restart NetworkManager";
    enword = "sdcv --color '$@' | w3m -graph";
    lukesmith = "cd ~/Videos/Luke\\ Smith/ && ls";
    scim = "sc-im";
    pomodoro = "termdown 1500";
    pv = "pipe-viewer";
    cfs = "vim ~/.local/bin/snippets";
    tmp = "cd /tmp && ls -a";
    cft = "vim ~/.config/tmux/tmux.conf";
    remastered = "cd /home/jonash/code/python/python-developer-bootcamp-tuomas-kivioja/remastered && ls";
    aic = "ascii-image-converter";
    website = "cd ~/repos/github/website-jonashxyz/jonashxyz/ && ls";
    update_website = "rsync -vrP --delete-after /home/jonash/repos/github/website-jonashxyz/jonashxyz/public/ root@jonash.xyz:/var/www/jonashxyz/";
    update-all-github-repos="dotfiles-sync-github && obsidian-sync-github && code-sync-github && website-sync-github-jonashxyz && wallpaper-sync-github && cv-sync-github && nixos-config-sync-github";
    ms = "mailsync";
    kindle = "cd /mnt/kindle/documents/Downloads/Books/ && ls";
    reading = "bat ~/vimwiki/2024.wiki";
    sb = "cd ~/repos/github/obsidian/ && ll";
    lg = "lazygit";
    scripts = "cd ~/dotfiles-nix/scripts/.local/bin/ && ls";
    hss = "hugo server --noHTTPCache";
    nb = "newsboat";
    ga = "git add";
    gP = "git push";
    gp = "git pull";
    gpr = "git pull --rebase";
    gs = "git status";
    gd = "git diff";
    gb = "git branch";
    gl = "git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit";
    gc = "git commit";
    gcm = "git commit -m";
    gco = "git checkout";
    gf = "git fetch";
    k = "kubectl";
    kgp = "kubectl get pods";
    fishies = "asciiquarium";
    fp = "fzf --preview 'bat --style=numbers --color=always --line-range :500 {}'";
    matrix = "mpv -fs --loop-playlist=inf ~/Videos/screensavers/matrix.webm";
    lastmod = "find . -type f -not -path '*/\\.*' -exec ls -lrt {} +";
    cfq = "v ~/.config/qutebrowser/config.py";
    brightness_reduce = "brightnessctl set 5%";
    brightness_max = "brightnessctl set 100%";
    lzd = "lazydocker";
    wallpapers = "cd ~/repos/github/wallpapers/ && ls";
    ff = "fastfetch";
    cv = "cd ~/repos/github/CV && ls";
    cfk = "vim ~/.config/kitty/kitty.conf";
    nconfig = "sudo nvim /etc/nixos/configuration.nix";
    cfh = "nvim ~/.config/hypr/hyprland.conf";
    youtube = "youtube-tui";
    rofi = "rofi -show drun";
    nconf = "cd ~/repos/github/nixos-config/ && la ";
    nconfig-backup = "/home/jonash/dotfiles-nix/scripts/.local/bin/nixos-backup";
    podcasts = "cd ~/Videos/podcasts/ && la";
    nfu = "sudo nix flake update";
    cfy = "vim ~/.config/yazi/yazi.toml";
    fr = "sudo nixos-rebuild switch --flake ~/repos/github/nixos-config/#$(hostname)";
    frd = "sudo nixos-rebuild dry-run --flake ~/repos/github/nixos-config/#$(hostname)";
    ghrepos="cd ~/repos/github/ && ls" ;
    recordings = "cd ~/recordings/ && ls";

  };
}
